/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package grafica;

import java.awt.Color;
import java.net.URL;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.ImageIcon;

/**
 *
 * @author Fabri
 */
public class Frm2PlacaOpciones extends javax.swing.JFrame {

    /**
     * Creates new form FrmOpcionesCargas
     */

    private boolean menuAbierto;
    private boolean menuMoviendose;
    
    private int posicionSeleccionada;
    private String medidaSeleccionada;
    
    public Frm2PlacaOpciones() {
        initComponents();
        lblBtnAtras.setVisible(false);
        setTitle("PR: Dos placas opciones | Equipo Dinamita");
        URL icono = getClass().getResource("/grafica/img/Logo_Proyecto.png");
        ImageIcon imagenIcono = new ImageIcon(icono);
        this.setIconImage( imagenIcono.getImage());
        this.setResizable(false);
        setLocationRelativeTo(null);
        lblAreaHover.setVisible(false);
        lblLargoAnchoHover.setVisible(false);
        medidaSeleccionada = "Area";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbtnAbrirMenu = new logica.JLabelRotar();
        jPanelMenu = new javax.swing.JPanel();
        lbtnVolverAtras = new javax.swing.JLabel();
        lbtnIrCargas = new javax.swing.JLabel();
        lbtnIrCreditos = new javax.swing.JLabel();
        lbtnSalir = new javax.swing.JLabel();
        lbtnIrLinea = new javax.swing.JLabel();
        lblMenuFondo = new javax.swing.JLabel();
        lblBtnSiguiente = new javax.swing.JLabel();
        lblBtnAtras = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblLargoAnchoHover = new javax.swing.JLabel();
        lblAreaHover = new javax.swing.JLabel();
        lblLargoAnchoText = new javax.swing.JLabel();
        lblAreaText = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();
        jPanelPantallaNegra = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbtnAbrirMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafica/img/botonAbrirMenu.png"))); // NOI18N
        lbtnAbrirMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbtnAbrirMenuMouseClicked(evt);
            }
        });
        getContentPane().add(lbtnAbrirMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 60));

        jPanelMenu.setBackground(new java.awt.Color(255, 255, 255));
        jPanelMenu.setFocusable(false);
        jPanelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbtnVolverAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbtnVolverAtrasMouseClicked(evt);
            }
        });
        jPanelMenu.add(lbtnVolverAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 400, 50));

        lbtnIrCargas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbtnIrCargasMouseClicked(evt);
            }
        });
        jPanelMenu.add(lbtnIrCargas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 400, 60));

        lbtnIrCreditos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbtnIrCreditosMouseClicked(evt);
            }
        });
        jPanelMenu.add(lbtnIrCreditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 400, 60));

        lbtnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbtnSalirMouseClicked(evt);
            }
        });
        jPanelMenu.add(lbtnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 400, 60));

        lbtnIrLinea.setText("jLabel1");
        lbtnIrLinea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbtnIrLineaMouseClicked(evt);
            }
        });
        jPanelMenu.add(lbtnIrLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 400, 60));

        lblMenuFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafica/img/menuDeslizablePlaca.png"))); // NOI18N
        jPanelMenu.add(lblMenuFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 560));

        getContentPane().add(jPanelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -560, 408, 560));

        lblBtnSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafica/img/BtnSiguienteArreglado.png"))); // NOI18N
        lblBtnSiguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBtnSiguienteMouseClicked(evt);
            }
        });
        getContentPane().add(lblBtnSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 240, 80, 100));

        lblBtnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafica/img/BtnAtrasArreglado.png"))); // NOI18N
        lblBtnAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBtnAtrasMouseClicked(evt);
            }
        });
        getContentPane().add(lblBtnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 90, 100));

        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 760, 420));

        lblLargoAnchoHover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafica/img/FlechaVerde.png"))); // NOI18N
        getContentPane().add(lblLargoAnchoHover, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 60, 130, 50));

        lblAreaHover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafica/img/FlechaVerde.png"))); // NOI18N
        getContentPane().add(lblAreaHover, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, 130, 50));

        lblLargoAnchoText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLargoAnchoTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLargoAnchoTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLargoAnchoTextMouseExited(evt);
            }
        });
        getContentPane().add(lblLargoAnchoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 280, 40));

        lblAreaText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAreaTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAreaTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAreaTextMouseExited(evt);
            }
        });
        getContentPane().add(lblAreaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 280, 40));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafica/img/2PlacasOpcion0Area.png"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 560));

        jPanelPantallaNegra.setOpaque(false);

        javax.swing.GroupLayout jPanelPantallaNegraLayout = new javax.swing.GroupLayout(jPanelPantallaNegra);
        jPanelPantallaNegra.setLayout(jPanelPantallaNegraLayout);
        jPanelPantallaNegraLayout.setHorizontalGroup(
            jPanelPantallaNegraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        jPanelPantallaNegraLayout.setVerticalGroup(
            jPanelPantallaNegraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelPantallaNegra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblBtnSiguienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBtnSiguienteMouseClicked
        if(posicionSeleccionada < 2){
            posicionSeleccionada++;
        }
        actualizarImagen();
    }//GEN-LAST:event_lblBtnSiguienteMouseClicked

    private void lblBtnAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBtnAtrasMouseClicked
        if(posicionSeleccionada > 0){
            posicionSeleccionada = posicionSeleccionada - 1;
        }
        actualizarImagen();
    }//GEN-LAST:event_lblBtnAtrasMouseClicked

    void actualizarImagen(){
        switch(posicionSeleccionada){
            case 0:
                ImageIcon icon = new ImageIcon(FrmMenu.class.getResource("/grafica/img/2PlacasOpcion0"+medidaSeleccionada+".png"));
                lblFondo.setIcon(icon);
                lblBtnAtras.setVisible(false);
                lblBtnSiguiente.setVisible(true);
                break;
            case 1: 
                icon = new ImageIcon(FrmMenu.class.getResource("/grafica/img/2PlacasOpcion1"+medidaSeleccionada+".png"));
                lblFondo.setIcon(icon);
                lblBtnAtras.setVisible(true);
                lblBtnSiguiente.setVisible(true);
                break;
            case 2:
                icon = new ImageIcon(FrmMenu.class.getResource("/grafica/img/2PlacasOpcion2"+medidaSeleccionada+".png"));
                lblFondo.setIcon(icon);
                lblBtnAtras.setVisible(true);
                lblBtnSiguiente.setVisible(false);
                break;
        }
    }
    
    private void mostrarMenu(){
        Timer cronometro = new Timer();
        TimerTask mostrarMenuTimer = new TimerTask(){
            @Override
            public void run() {
                if(jPanelMenu.getY() < 0){
                    if(lbtnAbrirMenu.getRotation() < 7.83){
                        lbtnAbrirMenu.setRotation(lbtnAbrirMenu.getRotation() + 0.15);
                    }else{
                        lbtnAbrirMenu.setRotation(7.83);
                    }
                    menuMoviendose = true;
                    int nuevaY = jPanelMenu.getY() + 8;
                    jPanelMenu.setLocation(0, nuevaY);
                }else{
                    menuMoviendose = false;
                    cancel();
                }
            }   
        };
        cronometro.scheduleAtFixedRate(mostrarMenuTimer, 0, 5);
    }
    
    private void ocultarMenu(){
        Timer cronometro = new Timer();
        TimerTask mostrarMenuTimer = new TimerTask(){
            @Override
            public void run() {
                if(lbtnAbrirMenu.getRotation() > 0){
                        lbtnAbrirMenu.setRotation(lbtnAbrirMenu.getRotation() - 0.15);
                }else{
                        lbtnAbrirMenu.setRotation(0);
                }
                if(jPanelMenu.getY() > -jPanelMenu.getHeight()){
                    menuMoviendose = true;
                    int nuevaY = jPanelMenu.getY() - 8;
                    jPanelMenu.setLocation(0, nuevaY);
                }else{
                    menuMoviendose = false;
                    cancel();
                }
            }   
        };
        cronometro.scheduleAtFixedRate(mostrarMenuTimer, 0, 8);
    }
    
    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        if(medidaSeleccionada.equals("Area")){
            switch(posicionSeleccionada){
                case 0:
                    setVisible(false);
                    new Frm2PlacaOpcion1().setVisible(true);
                    break;
                case 1:
                    setVisible(false);
                    new Frm2PlacaOpcion0().setVisible(true);
                    break;
                case 2:
                    setVisible(false);
                    new Frm2PlacaOpcion2().setVisible(true);
                    break;
            }
        }else{
            switch(posicionSeleccionada){
                case 0:
                    setVisible(false);
                    new Frm2PlacaOpcion1LargoAncho().setVisible(true);
                    break;
                case 1:
                    setVisible(false);
                    new Frm2PlacaOpcion0LargoAncho().setVisible(true);
                    break;
                case 2:
                    setVisible(false);
                    new Frm2PlacaOpcion2LargoAncho().setVisible(true);
                    break;
            }
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    private void lbtnAbrirMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbtnAbrirMenuMouseClicked
        if(!menuMoviendose){
            if(menuAbierto){
                menuAbierto = false;
                ocultarMenu();
            }else{
                menuAbierto = true;
                mostrarMenu();
            }
        }
    }//GEN-LAST:event_lbtnAbrirMenuMouseClicked

    private void lbtnVolverAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbtnVolverAtrasMouseClicked
        setVisible(false);
        new FrmMenu().setVisible(true);
    }//GEN-LAST:event_lbtnVolverAtrasMouseClicked

    private void lbtnIrCargasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbtnIrCargasMouseClicked
        setVisible(false);
        new FrmOpcionesCargas().setVisible(true);
    }//GEN-LAST:event_lbtnIrCargasMouseClicked

    private void lbtnIrCreditosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbtnIrCreditosMouseClicked
        setVisible(false);
        new FrmCreditos().setVisible(true);
    }//GEN-LAST:event_lbtnIrCreditosMouseClicked

    private void lbtnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbtnSalirMouseClicked
        jPanelPantallaNegra.setOpaque(true);
        jPanelPantallaNegra.setBackground(new Color(0,0,0,0));
        Timer cronometro = new Timer();
        TimerTask ajustarOpacidad = new TimerTask(){
            @Override
            public void run() {
                if(jPanelPantallaNegra.getBackground().getAlpha() < 50){
                    jPanelPantallaNegra.setBackground(new Color(0,0,0,jPanelPantallaNegra.getBackground().getAlpha() + 1));
                }else{
                    System.exit(0);
                    cancel();
                }
            }
        };
        cronometro.scheduleAtFixedRate(ajustarOpacidad, 0, 50);
    }//GEN-LAST:event_lbtnSalirMouseClicked

    private void lbtnIrLineaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbtnIrLineaMouseClicked
        setVisible(false);
        new FrmOpcionesLineas().setVisible(true);
    }//GEN-LAST:event_lbtnIrLineaMouseClicked

    private void lblLargoAnchoTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLargoAnchoTextMouseEntered
        lblLargoAnchoHover.setVisible(true);
        lblAreaHover.setVisible(false);
    }//GEN-LAST:event_lblLargoAnchoTextMouseEntered

    private void lblLargoAnchoTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLargoAnchoTextMouseExited
        lblLargoAnchoHover.setVisible(false);
        lblAreaHover.setVisible(false);
    }//GEN-LAST:event_lblLargoAnchoTextMouseExited

    private void lblAreaTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAreaTextMouseEntered
        lblLargoAnchoHover.setVisible(false);
        lblAreaHover.setVisible(true);
    }//GEN-LAST:event_lblAreaTextMouseEntered

    private void lblAreaTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAreaTextMouseExited
        lblLargoAnchoHover.setVisible(false);
        lblAreaHover.setVisible(false);
    }//GEN-LAST:event_lblAreaTextMouseExited

    private void lblLargoAnchoTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLargoAnchoTextMouseClicked
        switch(posicionSeleccionada){
            case 0:
                ImageIcon icon = new ImageIcon(FrmMenu.class.getResource("/grafica/img/2PlacasOpcion0LargoAncho.png"));
                lblFondo.setIcon(icon);
                break;
            case 1:
                icon = new ImageIcon(FrmMenu.class.getResource("/grafica/img/2PlacasOpcion1LargoAncho.png"));
                lblFondo.setIcon(icon);
                break;
            case 2:
                icon = new ImageIcon(FrmMenu.class.getResource("/grafica/img/2PlacasOpcion2LargoAncho.png"));
                lblFondo.setIcon(icon);
                break;
        }
        medidaSeleccionada = "LargoAncho";
    }//GEN-LAST:event_lblLargoAnchoTextMouseClicked

    private void lblAreaTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAreaTextMouseClicked
        switch(posicionSeleccionada){
            case 0:
                ImageIcon icon = new ImageIcon(FrmMenu.class.getResource("/grafica/img/2PlacasOpcion0Area.png"));
                lblFondo.setIcon(icon);
                break;
            case 1:
                icon = new ImageIcon(FrmMenu.class.getResource("/grafica/img/2PlacasOpcion1Area.png"));
                lblFondo.setIcon(icon);
                break;
            case 2:
                icon = new ImageIcon(FrmMenu.class.getResource("/grafica/img/2PlacasOpcion2Area.png"));
                lblFondo.setIcon(icon);
                break;
        }
        medidaSeleccionada = "Area";
    }//GEN-LAST:event_lblAreaTextMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm2PlacaOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm2PlacaOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm2PlacaOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm2PlacaOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm2PlacaOpciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelMenu;
    private javax.swing.JPanel jPanelPantallaNegra;
    private javax.swing.JLabel lblAreaHover;
    private javax.swing.JLabel lblAreaText;
    private javax.swing.JLabel lblBtnAtras;
    private javax.swing.JLabel lblBtnSiguiente;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblLargoAnchoHover;
    private javax.swing.JLabel lblLargoAnchoText;
    private javax.swing.JLabel lblMenuFondo;
    private logica.JLabelRotar lbtnAbrirMenu;
    private javax.swing.JLabel lbtnIrCargas;
    private javax.swing.JLabel lbtnIrCreditos;
    private javax.swing.JLabel lbtnIrLinea;
    private javax.swing.JLabel lbtnSalir;
    private javax.swing.JLabel lbtnVolverAtras;
    // End of variables declaration//GEN-END:variables
}
