package grafica;

import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;

/**
 *
 * @author Paña
 */
public class FrmMenu extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public FrmMenu() {
        initComponents();
        setTitle("PS: Menú | Equipo Dinamita");
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblCampoElectrico = new javax.swing.JLabel();
        lblIntegrantes = new javax.swing.JLabel();
        btnCargas = new javax.swing.JButton();
        btnPlacas = new javax.swing.JButton();
        lblFondoMenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Comic Sans MS", 1, 40)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Proyecto de Física");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 430, 70));

        lblCampoElectrico.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        lblCampoElectrico.setForeground(new java.awt.Color(255, 255, 255));
        lblCampoElectrico.setText("Campo electrico generado por:");
        getContentPane().add(lblCampoElectrico, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 360, 70));

        lblIntegrantes.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblIntegrantes.setForeground(new java.awt.Color(255, 255, 255));
        lblIntegrantes.setText("María Noel Saldaña, Fabrizio Cobucci, Maykol Martínez, Diego Javier");
        getContentPane().add(lblIntegrantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 930, 70));

        btnCargas.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnCargas.setText("Cargas");
        btnCargas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargasActionPerformed(evt);
            }
        });
        getContentPane().add(btnCargas, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 190, -1));

        btnPlacas.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnPlacas.setText("Placas");
        btnPlacas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlacasActionPerformed(evt);
            }
        });
        getContentPane().add(btnPlacas, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, 190, -1));

        lblFondoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafica/img/Fondo.jpg"))); // NOI18N
        getContentPane().add(lblFondoMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCargasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargasActionPerformed
        FrmCargas frm = new FrmCargas();
        frm.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCargasActionPerformed

    private void btnPlacasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlacasActionPerformed
        FrmPlaca frm = new FrmPlaca();
        frm.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnPlacasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargas;
    private javax.swing.JButton btnPlacas;
    private javax.swing.JLabel lblCampoElectrico;
    private javax.swing.JLabel lblFondoMenu;
    private javax.swing.JLabel lblIntegrantes;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
