/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package grafica;

import java.net.URL;
import javax.swing.ImageIcon;

/**
 *
 * @author Fabri
 */
public class FrmOpcionesCargas extends javax.swing.JFrame {

    /**
     * Creates new form FrmOpcionesCargas
     */
    public FrmOpcionesCargas() {
        initComponents();
        setTitle("PR: Opciones cargas | Equipo Dinamita");
        URL icono = getClass().getResource("/grafica/img/Logo_Proyecto.png");
        ImageIcon imagenIcono = new ImageIcon(icono);
        this.setIconImage( imagenIcono.getImage());
        this.setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBtn3Carga = new javax.swing.JLabel();
        lblBtn1Carga = new javax.swing.JLabel();
        lblBtn2Carga = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBtn3Carga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBtn3CargaMouseClicked(evt);
            }
        });
        getContentPane().add(lblBtn3Carga, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 340, 340, 80));

        lblBtn1Carga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBtn1CargaMouseClicked(evt);
            }
        });
        getContentPane().add(lblBtn1Carga, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 140, 340, 80));
        getContentPane().add(lblBtn2Carga, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 240, 340, 80));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafica/img/FondoOpcionesCarga.png"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblBtn1CargaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBtn1CargaMouseClicked
        setVisible(false);
        new Frm1Carga().setVisible(true);
    }//GEN-LAST:event_lblBtn1CargaMouseClicked

    private void lblBtn3CargaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBtn3CargaMouseClicked
        setVisible(false);
        new Frm3CargaOpciones().setVisible(true);
    }//GEN-LAST:event_lblBtn3CargaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmOpcionesCargas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmOpcionesCargas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmOpcionesCargas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmOpcionesCargas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmOpcionesCargas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblBtn1Carga;
    private javax.swing.JLabel lblBtn2Carga;
    private javax.swing.JLabel lblBtn3Carga;
    private javax.swing.JLabel lblFondo;
    // End of variables declaration//GEN-END:variables
}
