package grafica;

import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import logica.Placa;
import logica.Placas;

public class FrmPlaca extends javax.swing.JFrame {

    public static Placas placas;

    /**
     * Creates new form NewJFrame
     */
    public FrmPlaca() {
        initComponents();
        miInicializador();
    }

    private Icon iconoRedimensionado(String url, JLabel lbl) {
        ImageIcon imagen = new ImageIcon(getClass().getResource(url));
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(lbl.getWidth(), lbl.getHeight(), 1));
        return icono;
    }

    private void miInicializador() {
        setResizable(false);
        this.rbnConMovimiento.setEnabled(false);
        this.rbnSinMovimiento.setEnabled(false);
        this.btnRepresentar.setEnabled(false);
        placas = new Placas();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblTitulo = new javax.swing.JLabel();
        lblDensidadSuperficial = new javax.swing.JLabel();
        txtSigma = new javax.swing.JTextField();
        lblX10 = new javax.swing.JLabel();
        txtExp = new javax.swing.JTextField();
        lblC = new javax.swing.JLabel();
        lblRepresentacion = new javax.swing.JLabel();
        rbnConMovimiento = new javax.swing.JRadioButton();
        rbnSinMovimiento = new javax.swing.JRadioButton();
        btnRepresentar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        lblPlaca = new javax.swing.JLabel();
        lblFondoMenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Comic Sans MS", 1, 40)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(51, 51, 51));
        lblTitulo.setText("Campo entre placas");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 390, 70));

        lblDensidadSuperficial.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblDensidadSuperficial.setForeground(new java.awt.Color(51, 51, 51));
        lblDensidadSuperficial.setText("Densidad superficial de carga:");
        getContentPane().add(lblDensidadSuperficial, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 280, 50));

        txtSigma.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtSigma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSigmaActionPerformed(evt);
            }
        });
        getContentPane().add(txtSigma, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 40, -1));

        lblX10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblX10.setForeground(new java.awt.Color(51, 51, 51));
        lblX10.setText("X 10 ^");
        getContentPane().add(lblX10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 60, 30));

        txtExp.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtExp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtExpActionPerformed(evt);
            }
        });
        getContentPane().add(txtExp, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 30, -1));

        lblC.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblC.setForeground(new java.awt.Color(51, 51, 51));
        lblC.setText("C");
        getContentPane().add(lblC, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 20, 30));

        lblRepresentacion.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblRepresentacion.setForeground(new java.awt.Color(51, 51, 51));
        lblRepresentacion.setText("Representación:");
        getContentPane().add(lblRepresentacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 130, 160, 50));

        buttonGroup1.add(rbnConMovimiento);
        rbnConMovimiento.setText("Con movimiento");
        rbnConMovimiento.setEnabled(false);
        rbnConMovimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnConMovimientoActionPerformed(evt);
            }
        });
        getContentPane().add(rbnConMovimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 200, -1, -1));

        buttonGroup1.add(rbnSinMovimiento);
        rbnSinMovimiento.setText("Sin movimiento");
        rbnSinMovimiento.setEnabled(false);
        rbnSinMovimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnSinMovimientoActionPerformed(evt);
            }
        });
        getContentPane().add(rbnSinMovimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 200, -1, -1));

        btnRepresentar.setText("Representar");
        btnRepresentar.setEnabled(false);
        btnRepresentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRepresentarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRepresentar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 260, -1, -1));

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, -1, -1));
        getContentPane().add(lblPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 140, 60, 140));
        getContentPane().add(lblFondoMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSigmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSigmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSigmaActionPerformed

    private void txtExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtExpActionPerformed

    private void rbnConMovimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnConMovimientoActionPerformed
        this.btnRepresentar.setEnabled(true);
    }//GEN-LAST:event_rbnConMovimientoActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        try {
            String url;
            double sigma = Double.valueOf(this.txtSigma.getText()).doubleValue();
            sigma *= Math.pow(10.0D, Integer.valueOf(this.txtExp.getText()).intValue());
            placas.agregar(new Placa(sigma));
            this.rbnConMovimiento.setEnabled(true);
            this.rbnSinMovimiento.setEnabled(true);
            this.txtSigma.setText((String) null);
            this.txtExp.setText((String) null);

            if (sigma > 0.0D) {
                url = "img/PlacaPos.png";
            } else if (sigma < 0.0D) {
                url = "img/PlacaNeg.png";
            } else {

                url = "img/PlacaNeutra.png";
            }
            this.lblPlaca.setIcon(iconoRedimensionado(url, this.lblPlaca));
        } catch (Exception ex) {
            String st = "Ingrese un valor para la placa";
            JOptionPane.showMessageDialog(null, st);
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void rbnSinMovimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnSinMovimientoActionPerformed
        this.btnRepresentar.setEnabled(true);
    }//GEN-LAST:event_rbnSinMovimientoActionPerformed

    private void btnRepresentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRepresentarActionPerformed
        if (placas.tamano() > 0) {
            dispose();
            if (this.rbnConMovimiento.isSelected()) {
                (new FrmPlacasConMov()).setVisible(true);
            } else {

                (new PlacasSinMov()).setVisible(true);
            }
        } else {

            JOptionPane.showMessageDialog(null, "Ingrese al menos una placa");
        }
    }//GEN-LAST:event_btnRepresentarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPlaca.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPlaca.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPlaca.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPlaca.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPlaca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnRepresentar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel lblC;
    private javax.swing.JLabel lblDensidadSuperficial;
    private javax.swing.JLabel lblFondoMenu;
    private javax.swing.JLabel lblPlaca;
    private javax.swing.JLabel lblRepresentacion;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblX10;
    private javax.swing.JRadioButton rbnConMovimiento;
    private javax.swing.JRadioButton rbnSinMovimiento;
    private javax.swing.JTextField txtExp;
    private javax.swing.JTextField txtSigma;
    // End of variables declaration//GEN-END:variables
}
