package grafica;

import java.awt.LayoutManager;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import logica.Vector;

/**
 *
 * @author Paña
 */
public class PlacasSinMov extends javax.swing.JFrame {

    private PanelPlacas panel1;
    private JPanel panelImagenes;
    private JLabel lblCarga;
    private PanelVector panelVector;
    private int contador;

    public PlacasSinMov() {
        initComponents();
        miInicializador();
    }

    private double AGrados(double ang) {
        return Math.round(Math.toDegrees(ang));
    }

    private void eliminarPanelVector() {
        if (this.contador > 0) {
            remove(0);
        } else {

            this.contador++;
        }
    }

    private void crearPanelVector() {
        this.panelVector = new PanelVector(this.panel1.getBounds());
        add(this.panelVector);
        setComponentZOrder(this.panelVector, 0);
    }

    private void miInicializador() {
        setResizable(false);
        this.txtCampo.setEditable(false);
        this.txtFuerza.setEditable(false);
        this.contador = 0;

        this.panelImagenes = new JPanel();
        this.panelImagenes.setBounds(40, 40, 700, 500);
        this.panelImagenes.setLayout((LayoutManager) null);
        this.panelImagenes.setOpaque(false);
        this.lblCarga = new JLabel();
        this.lblCarga.setSize(16, 16);
        this.panelImagenes.add(this.lblCarga);
        this.lblFondo.add(this.panelImagenes);

        this.panel1 = new PanelPlacas();
        this.lblFondo.add(this.panel1);
        this.panel1.addMouseListener(new MouseAdapter() {

            public void mouseClicked(MouseEvent e) {
                try {
                    if (PlacasSinMov.this.panel1.getComponentAt(e.getPoint()).equals(PlacasSinMov.this.panel1)) {
                        boolean bandera = true;
                        boolean bandera2 = true;
                        int xCarga = e.getX();
                        int yCarga = e.getY();
                        double valorCarga = Double.valueOf(PlacasSinMov.this.txtCarga.getText()).doubleValue();
                        valorCarga *= Math.pow(10.0D, Integer.valueOf(PlacasSinMov.this.txtCargaExp.getText()).intValue());
                        double campo = FrmPlaca.placas.sumarCampos(xCarga);
                        double fuerza = campo * valorCarga;
                        double anguloCampo = FrmPlaca.placas.anguloCampo(campo);
                        double anguloFuerza = FrmPlaca.placas.anguloFuerza(anguloCampo, valorCarga);

                        PlacasSinMov.this.eliminarPanelVector();
                        PlacasSinMov.this.crearPanelVector();
                        PlacasSinMov.this.panelVector.representacion(new Vector(campo, anguloCampo), e.getPoint(), valorCarga);
                        PlacasSinMov.this.panelVector.repaint();

                        if (campo == 0.0D) {
                            bandera = false;
                        }

                        if (valorCarga == 0.0D) {
                            bandera2 = false;
                        }

                        String strCampo = String.format("%6.2e", new Object[]{Double.valueOf(Math.abs(campo))}) + "N/C   ";
                        String strFuerza = String.format("%6.2e", new Object[]{Double.valueOf(Math.abs(fuerza))}) + "N   ";
                        if (bandera) {
                            strCampo = strCampo + PlacasSinMov.this.AGrados(anguloCampo) + "°";
                            if (bandera2) {
                                strFuerza = strFuerza + PlacasSinMov.this.AGrados(anguloFuerza) + "°";
                            }
                        }
                        PlacasSinMov.this.txtCampo.setText(strCampo);
                        PlacasSinMov.this.txtFuerza.setText(strFuerza);
                    }

                } catch (Exception ex) {
                    String st = "Ingrese un valor para la carga";
                    JOptionPane.showMessageDialog(null, st);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblC = new javax.swing.JLabel();
        txtCarga = new javax.swing.JTextField();
        lblTitulo = new javax.swing.JLabel();
        lblFuerza = new javax.swing.JLabel();
        lblX10 = new javax.swing.JLabel();
        txtCampo = new javax.swing.JTextField();
        txtCargaExp = new javax.swing.JTextField();
        lblCampo = new javax.swing.JLabel();
        lblCargaPrueba = new javax.swing.JLabel();
        txtFuerza = new javax.swing.JTextField();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblC.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblC.setText("C");

        txtCarga.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtCarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCargaActionPerformed(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Arial", 1, 40)); // NOI18N
        lblTitulo.setText("Datos");

        lblFuerza.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblFuerza.setText("Fuerza:");

        lblX10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblX10.setText("X 10 ^");

        txtCampo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCampoActionPerformed(evt);
            }
        });

        txtCargaExp.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtCargaExp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCargaExpActionPerformed(evt);
            }
        });

        lblCampo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblCampo.setText("Campo:");

        lblCargaPrueba.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblCargaPrueba.setText("Carga:");

        txtFuerza.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtFuerza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFuerzaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(70, 70, 70))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lblCampo)
                            .addGap(6, 6, 6)
                            .addComponent(txtCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(31, 31, 31)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblCargaPrueba)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(txtCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblX10)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtCargaExp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lblC)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblFuerza)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFuerza)))
                .addGap(0, 12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblTitulo)
                .addGap(33, 33, 33)
                .addComponent(lblCargaPrueba)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblX10)
                    .addComponent(txtCargaExp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblC))
                .addGap(77, 77, 77)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCampo)
                    .addComponent(txtCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFuerza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFuerza))
                .addGap(230, 230, 230))
        );

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafica/img/FondoConHoja.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(770, 770, 770)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(lblFondo)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(lblFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCargaActionPerformed

    private void txtCargaExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCargaExpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCargaExpActionPerformed

    private void txtCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCampoActionPerformed

    private void txtFuerzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFuerzaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFuerzaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlacasSinMov.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlacasSinMov.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlacasSinMov.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlacasSinMov.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlacasSinMov().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblC;
    private javax.swing.JLabel lblCampo;
    private javax.swing.JLabel lblCargaPrueba;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblFuerza;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblX10;
    private javax.swing.JTextField txtCampo;
    private javax.swing.JTextField txtCarga;
    private javax.swing.JTextField txtCargaExp;
    private javax.swing.JTextField txtFuerza;
    // End of variables declaration//GEN-END:variables
}
