package grafica;

import java.awt.LayoutManager;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import logica.Vector;

/**
 *
 * @author Paña
 */
public class PlacasSinMov extends javax.swing.JFrame {



    /**
     * Creates new form NewJFrame
     */
    public PlacasSinMov() {
        initComponents();
      
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblCargaPrueba = new javax.swing.JLabel();
        lblX10 = new javax.swing.JLabel();
        lblC = new javax.swing.JLabel();
        txtCarga = new javax.swing.JTextField();
        txtCargaExp = new javax.swing.JTextField();
        lblCampo = new javax.swing.JLabel();
        lblFuerza = new javax.swing.JLabel();
        txtCampo = new javax.swing.JTextField();
        txtFuerza = new javax.swing.JTextField();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Arial", 1, 40)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(51, 51, 51));
        lblTitulo.setText("Datos");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 150, 60));

        lblCargaPrueba.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblCargaPrueba.setForeground(new java.awt.Color(51, 51, 51));
        lblCargaPrueba.setText("Carga de prueba:");
        getContentPane().add(lblCargaPrueba, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 170, 30));

        lblX10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblX10.setForeground(new java.awt.Color(51, 51, 51));
        lblX10.setText("X 10 ^");
        getContentPane().add(lblX10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 60, 30));

        lblC.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblC.setForeground(new java.awt.Color(51, 51, 51));
        lblC.setText("C");
        getContentPane().add(lblC, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 20, 30));

        txtCarga.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtCarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCargaActionPerformed(evt);
            }
        });
        getContentPane().add(txtCarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 40, -1));

        txtCargaExp.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtCargaExp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCargaExpActionPerformed(evt);
            }
        });
        getContentPane().add(txtCargaExp, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 30, -1));

        lblCampo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblCampo.setForeground(new java.awt.Color(51, 51, 51));
        lblCampo.setText("Campo:");
        getContentPane().add(lblCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 80, 30));

        lblFuerza.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblFuerza.setForeground(new java.awt.Color(51, 51, 51));
        lblFuerza.setText("Fuerza:");
        getContentPane().add(lblFuerza, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 80, 30));

        txtCampo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCampoActionPerformed(evt);
            }
        });
        getContentPane().add(txtCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 120, -1));

        txtFuerza.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtFuerza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFuerzaActionPerformed(evt);
            }
        });
        getContentPane().add(txtFuerza, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 120, -1));
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCargaActionPerformed

    private void txtCargaExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCargaExpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCargaExpActionPerformed

    private void txtCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCampoActionPerformed

    private void txtFuerzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFuerzaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFuerzaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlacasSinMov.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlacasSinMov.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlacasSinMov.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlacasSinMov.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlacasSinMov().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblC;
    private javax.swing.JLabel lblCampo;
    private javax.swing.JLabel lblCargaPrueba;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblFuerza;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblX10;
    private javax.swing.JTextField txtCampo;
    private javax.swing.JTextField txtCarga;
    private javax.swing.JTextField txtCargaExp;
    private javax.swing.JTextField txtFuerza;
    // End of variables declaration//GEN-END:variables
}
